### PR TITLE
Remove unused Cabal dependency

### PR DESCRIPTION
**Pull request by charleso**
/cc @jystic @markhibberd

### CODE REVIEW

**Comment by jystic** [comment]
👍

**Comment by markhibberd** [comment]
Hard to remove tasty as well?

**Comment by markhibberd** [comment]
👍

**Comment by charleso** [comment]
Tasty is currently used by the tests. Would definitely love to get rid of. Suggestions?

**Comment by markhibberd** [comment]
@charleso Ignore me, sorry I thought it was a library dependency.

**Pull request merged**
